services:
    admin.event:
        class: AppBundle\Admin\EventAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Management", label: "Events" }
        arguments:
            - ~
            - AppBundle\Entity\Event
            - ~

    admin.organizer:
            class: AppBundle\Admin\OrganizerAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Management", label: "Organizer" }
            arguments:
                - ~
                - AppBundle\Entity\Organizer
                - ~
