services:
    app.form.type.event:
        class: AppBundle\Form\Type\EventType
        tags:
            - { name: form.type, alias: event }

    app.form.type.organizer:
        class: AppBundle\Form\Type\OrganizerType
        tags:
            - { name: form.type, alias: organizer }
